services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=carr@carrarasoftware.com.br"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  sciquiz:
    image: ghcr.io/carraravitor/sciquiz:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sciquiz.rule=Host(`carrarasoftware.com.br`)"
      - "traefik.http.routers.sciquiz.entrypoints=websecure"
      - "traefik.http.routers.sciquiz.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ~/sciquiz/db/:/sciquiz/db/
    deploy:
      mode: replicated
      replicas: 3
    restart: always

volumes:
  letsencrypt:
