CREATE TABLE IF NOT EXISTS nodes (id INTEGER PRIMARY KEY, name TEXT, lane INTEGER);
CREATE TABLE IF NOT EXISTS lanes (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS edges (id INTEGER PRIMARY KEY, source INTEGER, dest INTEGER);
